### ISSUE TITLE
Post encoding problems

### ISSUE THREAD

**Issue by bolderbrooklyn** [bolderbrooklyn/jbhannah.net-jekyll#5]
Some old posts fail to build on Heroku with the following error:

```
-----> Running: rake assets:precompile
       bundle exec compass compile -c compass.rb
       directory css/
          create css/screen.css
          create css/print.css
          create css/ie.css
       bundle exec jekyll
       Configuration from /tmp/build_eajw5in2btq0/_config.yml
       Building site: /tmp/build_eajw5in2btq0 -> /tmp/build_eajw5in2btq0/_site
       Build Failed
       Liquid Exception: incompatible character encodings: UTF-8 and ASCII-8BIT in post
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/liquid-2.4.1/lib/liquid/block.rb:92:in `join'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/liquid-2.4.1/lib/liquid/block.rb:92:in `render_all'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/liquid-2.4.1/lib/liquid/block.rb:82:in `render'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/liquid-2.4.1/lib/liquid/template.rb:124:in `render'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/liquid-2.4.1/lib/liquid/template.rb:132:in `render!'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/lib/jekyll/convertible.rb:101:in `do_layout'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/lib/jekyll/post.rb:195:in `render'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:200:in `block in render'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `each'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:199:in `render'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/lib/jekyll/site.rb:41:in `process'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/gems/jekyll-0.12.0/bin/jekyll:264:in `<top (required)>'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/bin/jekyll:19:in `load'
       /tmp/build_eajw5in2btq0/vendor/bundle/ruby/1.9.1/bin/jekyll:19:in `<main>'
       rake aborted!
       Command failed with status (1): [bundle exec jekyll...]
       /tmp/build_eajw5in2btq0/Rakefile:10:in `block (2 levels) in <top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
```

Posts that do this had previously had invalid characters. After all invalid characters had been corrected, the post still fails to compile, and this is the error message that results.

**Comment by bolderbrooklyn** [comment]
Maybe fixed by Ruby 2.0's defaulting to UTF-8?

**Comment by bolderbrooklyn** [comment]
Fixed using Ruby 2.0.

**Comment by bolderbrooklyn** [comment]
Still broken when pushing to Heroku.

**Comment by bolderbrooklyn** [comment]
Ultimately it turns out to have been a problem with bad characters in Gists included in posts, not in posts themselves.
